import { modelMetrics as m, communicationData as cd, blockchainEvents, auditLogs, localDataset as ds, federatedRounds } from '../services/mockData'
const local = 'Raw medical data stays local. Only privacy-protected model updates are exchanged.'
const demo = 'Demo data: replace with actual experimental results.'
export const pageConfigs = {
 rounds: { title: 'Federated Rounds', subtitle: 'Round history', table: { cols: ['Round','Status','Hospitals','Accuracy','F1','Aggregation','Privacy'], rows: federatedRounds.map(r => ['#0' + r.id, r.status, r.participants, r.accuracy + '%', r.f1 + '%', r.aggregation, r.privacy]) } },
 roundDetails: { title: 'Round Details', subtitle: 'Round timeline', steps: ['Global Model Initialized','Global Model Distributed','Hospital Local Training','Validation','Differential Privacy','Model Updates Received','Aggregation','Global Model Updated'], done: 6, stepsTitle: 'Timeline', bars: [['City Hospital',100],['Metro Hospital',100],['HealthCare Center',100],['Sunrise Medical Center',0]], barsTitle: 'Hospital progress (%)' },
 aggregation: { title: 'Quality-Aware Adaptive Aggregation', subtitle: 'Scoreᵢ = αDᵢ + βAᵢ + γRᵢ', banner: demo, note: 'D = dataset contribution, A = validation accuracy, R = client reliability. FedAvg weights by dataset size only; MedSecureFL combines dataset size, validation performance and client reliability.', table: { cols: ['Hospital','Dataset Size','Validation Accuracy','Reliability','Aggregation Weight'], rows: [['City Hospital',5240,'95.1%',0.97,0.42],['Metro Hospital',3980,'93.9%',0.94,0.31],['HealthCare Center',2760,'94.2%',0.91,0.27]] }, bars: [['FedAvg (size only)',93.1],['MedSecureFL (adaptive)',94.82]], barsTitle: 'Accuracy comparison (demo)' },
 globalModel: { title: 'Global Model', subtitle: m.name, stats: [['Version', m.version],['Framework', m.framework],['Rounds', m.rounds],['Status', m.status],['Global Accuracy', m.accuracy + '%'],['Global F1', m.f1 + '%']], steps: ['Input Image','Patch Embedding','Transformer Encoder','Attention Blocks','Classification Head','Prediction'], stepsTitle: 'Architecture' },
 results: { title: 'Results', subtitle: 'FedAvg vs MedSecureFL', banner: 'Prototype simulation data: replace with actual experimental results.', bars: [['Accuracy: FedAvg',93.1],['Accuracy: MedSecureFL',94.82],['F1: FedAvg',92.8],['F1: MedSecureFL',94.61]], barsTitle: 'Accuracy / F1 (demo)' },
 commCentral: { title: 'Communication', subtitle: 'Network-wide transfers', banner: local, stats: [['Raw Medical Data', cd.rawData],['Patient Records', cd.records],['Model Updates', cd.updates],['Global Model Transfers', cd.transfers]], steps: ['Central Server','Global Model','Hospital','Local Dataset','Local Training','Differential Privacy','Model Update','Central Server'], stepsTitle: 'Communication flow' },
 privacyCentral: { title: 'Privacy Audit', subtitle: 'Network-wide privacy status', banner: local, stats: [['Differential Privacy','ENABLED'],['Raw Data Isolation','ACTIVE'],['Model Update Only','ACTIVE'],['Patient Data Transfer',0],['Data Residency','LOCAL'],['Privacy Budget','ε = 4.0'],['Noise Mechanism','Gaussian']], steps: ['Hospital: Patient Data','Local Dataset','Local Training','Differential Privacy','Model Update','Central Server'], stepsTitle: 'Privacy boundary' },
 blockchain: { title: 'Permissioned Blockchain', subtitle: 'Network status: OPERATIONAL', banner: 'Only authorization and audit events are recorded. No medical data is stored on the blockchain.', stats: [['Registered Hospitals',4],['Verified',3],['Pending',1]], table: { cols: ['Block','Event','Hospital','Status','Timestamp'], rows: blockchainEvents } },
 settings: { title: 'Settings', subtitle: 'Account and preferences', note: 'Settings will be available in a later phase.' },
 myHospital: { title: 'My Hospital', subtitle: 'City Hospital', stats: [['Hospital ID','HOSP-001'],['Client ID','CLIENT-001'],['Client Status','ONLINE'],['Participation','8/8 rounds'],['Verification','VERIFIED'],['Current Round','#08'],['Administrator','City Hospital Admin'],['Registered','2026-01-12']] },
 dataset: { title: 'Local Dataset', subtitle: ds.name, banner: 'Your medical dataset stays inside the hospital environment.', stats: [['Images','5,240'],['Classes',7],['Raw Data Transfer','0 MB'],['Images Uploaded to Central Server',0]], bars: ds.dist, barsTitle: 'Class distribution' },
 modelUpdates: { title: 'Model Updates', subtitle: 'Your submissions only', table: { cols: ['Round','Model','Accuracy','F1','Differential Privacy','Status'], rows: [8,7,6].map((r, i) => ['#0' + r, 'ViT ' + m.version, [95.1,94.6,93.8][i] + '%', [94.8,94.2,93.5][i] + '%', 'ENABLED', 'COMPLETED']) } },
 privacyHospital: { title: 'Privacy', subtitle: 'Your hospital privacy status', banner: local, stats: [['Differential Privacy','ENABLED'],['Raw Dataset Transfer','0 MB'],['Patient Records Transfer',0],['Local Dataset','PROTECTED'],['Model Update','PRIVACY PROTECTED'],['Privacy Budget','ε = 4.0']], note: 'Status: within configured budget.' },
 commHospital: { title: 'Communication', subtitle: 'Your hospital only', banner: local, stats: [['Server → Hospital: Global Model', cd.perHospital],['Hospital → Server: Model Update', cd.perHospital],['Raw Data','0 MB']] },
 bcHospital: { title: 'Blockchain Identity', subtitle: 'Authorization status: VERIFIED', stats: [['Hospital ID','HOSP-001'],['Client ID','CLIENT-001'],['Blockchain Identity','0x3B1E...77A0']], steps: ['Hospital Registered','Identity Created','Central Authority Verified','Client Authorized','Round Participation','Model Update Submitted'], stepsTitle: 'Events' },
 audit: { title: 'Audit Logs', subtitle: 'Your hospital activity', table: { cols: ['Timestamp','Event','Round','Status'], rows: auditLogs } },
 federatedRound: { title: 'Federated Round #08', subtitle: 'Your participation', steps: ['Global Model Received','Local Dataset Loaded','Local Training Completed','Validation','Differential Privacy','Model Update Ready','Submitted'], stepsTitle: 'Progress' }
}
