export const Card = ({ title, children, className = '' }) => <div className={`rounded-xl border border-slate-200 bg-white p-5 ${className}`}>{title && <h3 className="mb-3 font-semibold text-navy-900">{title}</h3>}{children}</div>
const tone = { ACTIVE:'green', VERIFIED:'green', OK:'green', CONFIRMED:'green', READY:'green', ENABLED:'green', COMPLETED:'green', APPROVED:'green', PENDING:'amber', 'IN PROGRESS':'amber', REJECTED:'red' }
const cls = { green:'bg-emerald-50 text-emerald-700', amber:'bg-amber-50 text-amber-700', red:'bg-red-50 text-red-700', gray:'bg-slate-100 text-slate-600' }
export const Badge = ({ children, color = 'gray' }) => <span className={`inline-block rounded-full px-2.5 py-0.5 text-xs font-medium ${cls[color]}`}>{children}</span>
export const StatusBadge = ({ status }) => <Badge color={tone[status] || 'gray'}>{status}</Badge>
export const Button = ({ variant = 'primary', className = '', ...p }) => <button {...p} className={`rounded-lg px-4 py-2 text-sm font-medium transition disabled:opacity-50 ${{ primary:'bg-teal-600 text-white hover:bg-teal-500', outline:'border border-slate-300 bg-white text-navy-900 hover:bg-slate-50', danger:'border border-red-300 text-red-700 hover:bg-red-50' }[variant]} ${className}`} />
export const StatCard = ({ label, value }) => <Card><div className="text-sm text-slate-500">{label}</div><div className="mt-1 text-2xl font-semibold text-navy-900">{value}</div></Card>
export const PageHeader = ({ title, subtitle, children }) => <div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold text-navy-900">{title}</h1>{subtitle && <p className="text-slate-500">{subtitle}</p>}</div>{children}</div>
export const ProgressBar = ({ value }) => <div className="h-2 rounded bg-slate-200"><div className="h-2 rounded bg-teal-500" style={{ width: `${value}%` }} /></div>
export const Table = ({ cols, children }) => <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-slate-500">{cols.map(c => <th key={c} className="px-3 py-2 font-medium">{c}</th>)}</tr></thead><tbody>{children}</tbody></table></div>
export const Steps = ({ steps, done = steps.length }) => <ol className="space-y-3">{steps.map((s, i) => <li key={s + i} className="flex items-center gap-3"><span className={`flex h-6 w-6 items-center justify-center rounded-full text-xs ${i < done ? 'bg-teal-600 text-white' : 'bg-slate-200 text-slate-500'}`}>{i < done ? '✓' : i + 1}</span><span className="text-sm">{s}</span></li>)}</ol>
export const Bars = ({ data, max }) => { const m = max || Math.max(...data.map(d => d[1])); return <div className="space-y-2">{data.map(([l, v]) => <div key={l}><div className="flex justify-between text-xs"><span>{l}</span><span>{v}</span></div><ProgressBar value={(v / m) * 100} /></div>)}</div> }
export const Banner = ({ children }) => <div className="mb-6 rounded-lg border border-teal-200 bg-teal-50 px-4 py-3 text-sm text-teal-800">{children}</div>
export const EmptyState = ({ text }) => <div className="rounded-xl border border-dashed border-slate-300 p-10 text-center text-slate-500">{text}</div>
export const LoadingSpinner = () => <div className="h-6 w-6 animate-spin rounded-full border-2 border-teal-600 border-t-transparent" />
